name: Pull Request Main Branch
on:
  pull_request:
    branches:
      - main
jobs:
  Notify_Slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          author_name: mainブランチにPRされました。レビューをお願いします！！
          fields: repo,message,commit,author
          mention: "channel"
          if_mention: always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
